#include <Arduino.h>
#include <WiFi.h>
#include <WebServer.h>
#include <HTTPClient.h>
#include "WebSocketsServer.h"
#include "browser.h"
#include "config.h"
#include "display.h"
#include "timerLogic.h"
#include "loraRemotes.h"
#include "espnowRemotes.h"
#include <ElegantOTA.h>

// Forward declarations (previously auto-generated by the Arduino .ino build step)
void initNetwork();
void startAPMode();
void handleRoot();
void handleControl();
void handleSetTime();
void handleSetMatchTime();
void updateClient();
void onWebSocketEvent(uint8_t num, WStype_t type, uint8_t * payload, size_t length);
void handleSetWiFi();
void handleClearWiFi();
void pushSyncCommand(const char* cmd);
void pushSyncSetting(const char* type, const String& value);
void pushAllSyncSettings();
void applyDigitColor(uint32_t hex);
void applyBrightnessSetting(int val);
void applyDisplayInverted(bool inverted);
void applySettingsAudio(bool enabled, bool remoteEnabled, uint8_t output);
void applyReadyRequired(bool required);
void applyTapoutEnabled(bool enabled);
void applyClockMode(int hour, int minute, int s);
void applyOneOffTime(int m, int s);
void applyMatchTime(int m, int s);
void connectWiFi();
void checkWiFiConnection();
void loadSavedSettings();

// Fixed-capacity ring buffer instead of std::queue<String>: the old version
// did a String heap allocation on every push/pop, including one *inside*
// portENTER_CRITICAL/portEXIT_CRITICAL - allocating while a spinlock is held
// is asking for trouble, plus it fragments the heap over long uptimes. This
// version only ever memcpy's fixed-size buffers inside the critical section.
#define CMD_QUEUE_SIZE 8
#define CMD_MAX_LEN 16
// Not volatile: all access is already serialized by portENTER/EXIT_CRITICAL.
static char commandQueue[CMD_QUEUE_SIZE][CMD_MAX_LEN];
static uint8_t cmdQueueHead = 0;
static uint8_t cmdQueueTail = 0;
static uint8_t cmdQueueCount = 0;
portMUX_TYPE queueMux = portMUX_INITIALIZER_UNLOCKED;

void queueCommand(const char* cmd) {
    portENTER_CRITICAL(&queueMux);
    if (cmdQueueCount < CMD_QUEUE_SIZE) {
        strncpy(commandQueue[cmdQueueTail], cmd, CMD_MAX_LEN - 1);
        commandQueue[cmdQueueTail][CMD_MAX_LEN - 1] = '\0';
        cmdQueueTail = (cmdQueueTail + 1) % CMD_QUEUE_SIZE;
        cmdQueueCount++;
    }
    portEXIT_CRITICAL(&queueMux);
}

Preferences preferences;

// Instantiate the objects here
WebServer server(80);
WebSocketsServer webSocket = WebSocketsServer(81);

const char* apSSID = "TimerSetup";
const char* apPassword = "12345678";

int countdown_time = 120; // Default to 2 minutes (120 seconds)
int current_time = countdown_time;
bool timeSelState = false;

// Set once, the first time WiFi.status() reports WL_CONNECTED via the
// normal STA path (never set by the AP-mode fallback). Gates the
// auto-reconnect check in loop() - if this unit was never told to join a
// network in the first place, boot behavior (stay in AP mode) is
// unchanged; a later drop is only "reconnected" if it had actually
// connected at some point, since that's what indicates someone intended
// this unit to be on a network.
bool wifiEverConnected = false;
bool blueReady = false;
bool redReady = false;
bool readyRequired = false; // default to requiring ready-up

bool border_toggle = 1;

// Remote pairing state - a role can be bound via LoRa, ESP-NOW, or both at
// once (identity storage lives in loraRemotes.cpp / espnowRemotes.cpp
// respectively). redPaired/bluePaired/judgePaired are the combined,
// UI-facing flags; see the comment in config.h.
bool pairingMode = false;
unsigned long pairingModeStarted = 0;
#define PAIRING_MODE_TIMEOUT_MS 15000 // auto-cancel if nothing pairs in time, rather than hanging until a reboot
bool redPaired = false, bluePaired = false, judgePaired = false;
bool redLoraPaired = false, blueLoraPaired = false, judgeLoraPaired = false;
bool redEspNowPaired = false, blueEspNowPaired = false, judgeEspNowPaired = false;

void recomputePairedFlags() {
    redPaired = redLoraPaired || redEspNowPaired;
    bluePaired = blueLoraPaired || blueEspNowPaired;
    judgePaired = judgeLoraPaired || judgeEspNowPaired;
}

void clearRemotes() {
    Serial.println("[SYSTEM] Wiping remote bindings (LoRa + ESP-NOW)...");
    loraClearRemotes();
    espnowClearRemotes();
    recomputePairedFlags();
    Serial.println("[SYSTEM] All remotes wiped.");
}

int countdown = 3; //number of seconds until match start

int scrollIndex = 0;
unsigned long lastScrollTime = 0;
volatile bool needsLEDUpdate = false;
unsigned long startAttemptTime = 0;

int currentState = CONNECTING;

bool displayInverted = false;

bool tapoutEnabled = true;
bool tapoutInitiatorIsBlue = true;

bool audioEnabled = true;
bool remoteAudioEnabled = true;
uint8_t audioOutputSelect = 0; // 0 = Buzzer, 1 = Relay
uint32_t beepEndTime = 0;
bool beepActive = false;

// main.ino Globals
CRGB digitColor = CRGB::Red; // Default
uint8_t systemBrightness = 127;

bool isDoubleSided = true;

// Multi-timer sync: lets one timer's web page drive another over WiFi (both
// already have to be on the same local network for their own web UI, so this
// reuses that link instead of adding a second radio hop). Empty = standalone
// (default). Point-to-point by design - configuring both timers to target
// each other is fine, since only handleControl()'s locally-originated branch
// ever pushes (see pushSyncCommand call sites), never the /synccmd receiver,
// so a received command can't bounce back and forth forever.
String syncTargetIP = "";

// The SSID this unit is configured to join, cached at connectWiFi() time so
// /status doesn't need a flash (NVS) read on every poll. Empty if never
// configured (fresh unit, boots straight to AP mode).
String configuredSSID = "";

// Per-unit display label ("Mat 1", "Mat 2", ...) so operators running
// several timers can tell them apart at a glance. Deliberately never synced
// to the multi-timer sync target - each unit needs its own distinct name,
// so pushing it would defeat the point.
String timerName = "";

void initNetwork() {
    connectWiFi();

    server.on("/", handleRoot);
    server.on("/control", handleControl);
    server.on("/settime", handleSetTime);
    server.on("/setmatchtime", handleSetMatchTime);
    server.on("/setwifi", handleSetWiFi);
    server.on("/clearwifi", handleClearWiFi);

    // Full reset: every preference namespace this firmware uses ("settings"
    // covers colors/brightness/audio/tapout/ready/display-flip/sync target/
    // clock-active; "wifi" covers the saved SSID/password; "bot-timer"
    // covers remote pairing) - cleared wholesale with preferences.clear()
    // rather than removing individual keys, so a setting added here later
    // is automatically covered too. Reboot re-reads everything, which is
    // where each preferences.getX(key, default) call supplies the factory
    // default for whatever's now missing.
    server.on("/factoryreset", []() {
        Serial.println("[SYSTEM] Factory reset requested - wiping all saved settings...");

        const char* namespaces[] = { "settings", "wifi", "bot-timer" };
        for (const char* ns : namespaces) {
            preferences.begin(ns, false);
            preferences.clear();
            preferences.end();
        }

        server.send(200, "text/html", "<h1>Factory Reset Complete! Rebooting...</h1>");
        delay(3000);
        ESP.restart();
    });
    
    server.on("/pair", []() {
        pairingMode = true;
        pairingModeStarted = millis();
        Serial.println("[SYSTEM] Pairing Mode Active");
        server.send(200, "text/plain", "Pairing Mode Active");
    });

    server.on("/clear_remotes", []() {
        clearRemotes();
        server.send(200, "text/plain", "Remotes Wiped");
    });

    server.on("/setname", []() {
        String name = server.arg("name");
        name.trim();
        if (name.length() > 24) name = name.substring(0, 24); // keep the header readable

        timerName = name;
        preferences.begin("settings", false);
        preferences.putString("timerName", timerName);
        preferences.end();

        server.send(200, "text/plain", "Name Saved");
    });

    server.on("/setsyncip", []() {
        String ip = server.arg("ip");
        ip.trim();

        if (ip.length() == 0) {
            syncTargetIP = "";
            preferences.begin("settings", false);
            preferences.remove("syncIP");
            preferences.end();
            server.send(200, "text/plain", "Sync target cleared");
            return;
        }

        IPAddress test;
        if (!test.fromString(ip)) {
            server.send(400, "text/plain", "Invalid IP address");
            return;
        }

        syncTargetIP = ip;
        preferences.begin("settings", false);
        preferences.putString("syncIP", syncTargetIP);
        preferences.end();

        // Newly bound - push everything this unit currently has, not just
        // future changes, so the two timers start out in sync immediately
        // instead of waiting for the next individual setting to drift over.
        // Deliberately settings only (color/brightness/flip/audio/ready/
        // tapout/clock), not match-control state - forcing the peer to
        // start/pause/reset a possibly-active match just because someone
        // typed an IP address would be a surprising side effect.
        pushAllSyncSettings();

        server.send(200, "text/plain", "Sync target saved");
    });

    // Received end of the sync link (see pushSyncCommand). Deliberately only
    // ever queues locally - never re-pushes to this unit's own syncTargetIP -
    // so two timers configured to sync each other can't echo forever.
    server.on("/synccmd", []() {
        String cmd = server.arg("cmd");
        if (cmd == "start" || cmd == "pause" || cmd == "reset" || cmd == "clockOff") {
            queueCommand(cmd.c_str());
        }
        server.send(200, "text/plain", "OK");
    });

    // Received end of the settings sync link (see pushSyncSetting). Each
    // apply* helper is the same one the locally-originated /setXXX handler
    // itself calls, so a synced setting takes effect and persists exactly
    // like a locally-made change - the only difference is this path never
    // calls pushSyncSetting() itself, so two timers configured to sync each
    // other can't echo a setting back and forth forever.
    server.on("/syncsetting", []() {
        String type = server.arg("type");
        String value = server.arg("value");

        if (type == "color") {
            applyDigitColor(strtoul(value.c_str(), NULL, 16));
        } else if (type == "brightness") {
            applyBrightnessSetting(value.toInt());
        } else if (type == "flip") {
            applyDisplayInverted(value == "true");
        } else if (type == "audio") {
            int c1 = value.indexOf(',');
            int c2 = value.indexOf(',', c1 + 1);
            if (c1 > 0 && c2 > c1) {
                applySettingsAudio(value.substring(0, c1) == "true",
                                    value.substring(c1 + 1, c2) == "true",
                                    value.substring(c2 + 1).toInt());
            }
        } else if (type == "readyRequired") {
            applyReadyRequired(value == "true");
        } else if (type == "tapoutEnabled") {
            applyTapoutEnabled(value == "true");
        } else if (type == "time") {
            int c1 = value.indexOf(',');
            if (c1 > 0) {
                applyMatchTime(value.substring(0, c1).toInt(), value.substring(c1 + 1).toInt());
            }
        } else if (type == "oneOffTime") {
            int c1 = value.indexOf(',');
            if (c1 > 0) {
                applyOneOffTime(value.substring(0, c1).toInt(), value.substring(c1 + 1).toInt());
            }
        } else if (type == "clockOn") {
            int c1 = value.indexOf(',');
            int c2 = value.indexOf(',', c1 + 1);
            if (c1 > 0 && c2 > c1) {
                applyClockMode(value.substring(0, c1).toInt(),
                                value.substring(c1 + 1, c2).toInt(),
                                value.substring(c2 + 1).toInt());
            }
        }

        server.send(200, "text/plain", "OK");
    });

    server.on("/status", []() {
      String json = "{";
      json += "\"pairing\":" + String(pairingMode ? "true" : "false") + ",";
      if (pairingMode) {
          long secondsLeft = (PAIRING_MODE_TIMEOUT_MS - (long)(millis() - pairingModeStarted)) / 1000;
          json += "\"pairingSecondsLeft\":" + String(secondsLeft < 0 ? 0 : secondsLeft) + ",";
      }
      json += "\"readyRequired\":" + String(readyRequired ? "true" : "false") + ",";
      json += "\"tapoutEnabled\":" + String(tapoutEnabled ? "true" : "false") + ",";
      json += "\"audioEnabled\":" + String(audioEnabled ? "true" : "false") + ",";
      json += "\"remoteAudioEnabled\":" + String(remoteAudioEnabled ? "true" : "false") + ",";
      json += "\"audioOutput\":" + String(audioOutputSelect) + ",";
        
      json += "\"state\":\"";
      if (currentState == CLOCK_MODE) json += "CLOCK_MODE";
      else if (currentState == RUNNING) json += "RUNNING";
      else if (currentState == PAUSED) json += "PAUSED";
      else if (currentState == PRE_COUNTDOWN_LOOP) json += "PRE_COUNTDOWN_LOOP";
      else if (currentState == FINISHED) json += "FINISHED";
      else if (currentState == TAPOUT) json += "TAPOUT";
      else json += "IDLE";
      json += "\",";

      json += "\"tapoutBlue\":" + String(tapoutInitiatorIsBlue ? "true" : "false") + ",";
      json += "\"red\":" + String(redPaired ? "true" : "false") + ",";
      json += "\"blue\":" + String(bluePaired ? "true" : "false") + ",";
      json += "\"judge\":" + String(judgePaired ? "true" : "false") + ",";
      json += "\"redLora\":" + String(redLoraPaired ? "true" : "false") + ",";
      json += "\"redEspNow\":" + String(redEspNowPaired ? "true" : "false") + ",";
      json += "\"blueLora\":" + String(blueLoraPaired ? "true" : "false") + ",";
      json += "\"blueEspNow\":" + String(blueEspNowPaired ? "true" : "false") + ",";
      json += "\"judgeLora\":" + String(judgeLoraPaired ? "true" : "false") + ",";
      json += "\"judgeEspNow\":" + String(judgeEspNowPaired ? "true" : "false") + ",";
      json += "\"brightness\":" + String(systemBrightness) + ",";
      json += "\"displayInverted\":" + String(displayInverted ? "true" : "false") + ",";
      json += "\"myIP\":\"" + WiFi.localIP().toString() + "\",";
      json += "\"syncTargetIP\":\"" + syncTargetIP + "\",";
      json += "\"wifiSSID\":\"" + configuredSSID + "\",";
      json += "\"timerName\":\"" + timerName + "\",";
      json += "\"loraRadioPresent\":" + String(loraRadioPresent() ? "true" : "false") + ",";

      char hexColor[7];
      snprintf(hexColor, sizeof(hexColor), "%02X%02X%02X", digitColor.r, digitColor.g, digitColor.b);
      json += "\"digitColor\":\"" + String(hexColor) + "\",";
      
      int minutes = current_time / 60;
      int seconds = current_time % 60;
      char timeBuf[6];
      snprintf(timeBuf, sizeof(timeBuf), "%02d:%02d", minutes, seconds);
      json += "\"currentTime\":\"" + String(timeBuf) + "\",";
      json += "\"preCountdown\":" + String(countdown) + ",";
      json += "\"redReady\":" + String(redReady ? "true" : "false") + ",";
      json += "\"blueReady\":" + String(blueReady ? "true" : "false");
      json += "}";
      
      server.send(200, "application/json", json);
    });

    server.on("/setcolor", []() {
        if (currentState == RUNNING || currentState == PAUSED || currentState == PRE_COUNTDOWN_LOOP) {
            server.send(403, "text/plain", "Locked during match");
            return;
        }

        String hexStr = server.arg("hex");
        uint32_t hex = strtol(hexStr.c_str(), NULL, 16);
        
        uint8_t r = (hex >> 16) & 0xFF;
        uint8_t g = (hex >> 8)  & 0xFF;
        uint8_t b = hex & 0xFF;

        if (r > 180 && g > 180 && b > 180) {
            Serial.println("[SAFETY] Blinding near-white color detected. Saving and applying as a soft gray floor.");
            hex = 0x323232;
        }

        applyDigitColor(hex);

        char hexOut[7];
        snprintf(hexOut, sizeof(hexOut), "%06X", hex);
        pushSyncSetting("color", hexOut);

        server.send(200, "text/plain", "Color Processed & Saved");
    });

    server.on("/setbrightness", []() {
      if (currentState == RUNNING || currentState == PAUSED || currentState == PRE_COUNTDOWN_LOOP) {
          server.send(403, "text/plain", "Locked during match");
          return;
      }
      int requestedVal = server.arg("val").toInt();
      applyBrightnessSetting(requestedVal);
      pushSyncSetting("brightness", String(systemBrightness));

      server.send(200, "text/plain", "Brightness Set");
    });

    server.on("/synctime", []() {
        if (currentState != IDLE && currentState != CLOCK_MODE) {
            server.send(403, "text/plain", "Timer is active!");
            return;
        }
        int hour = server.arg("h").toInt();
        int minute = server.arg("m").toInt();
        int s = server.arg("s").toInt();

        applyClockMode(hour, minute, s);
        pushSyncSetting("clockOn", String(hour) + "," + String(minute) + "," + String(s));

        server.send(200, "text/plain", "Clock Seeded");
    });

    server.on("/flip", []() {
      applyDisplayInverted(!displayInverted);
      pushSyncSetting("flip", displayInverted ? "true" : "false");

      server.send(200, "text/plain", displayInverted ? "Inverted" : "Normal");
    });

    server.on("/setaudio", []() {
        if (currentState == RUNNING || currentState == PAUSED || currentState == PRE_COUNTDOWN_LOOP) {
            server.send(403, "text/plain", "Locked during match");
            return;
        }
        
        bool enabled = server.hasArg("enabled") ? (server.arg("enabled") == "true") : audioEnabled;
        bool remoteEnabled = server.hasArg("remoteEnabled") ? (server.arg("remoteEnabled") == "true") : remoteAudioEnabled;
        uint8_t output = server.hasArg("output") ? server.arg("output").toInt() : audioOutputSelect;

        applySettingsAudio(enabled, remoteEnabled, output);
        pushSyncSetting("audio", String(audioEnabled ? "true" : "false") + "," +
                                  String(remoteAudioEnabled ? "true" : "false") + "," +
                                  String(audioOutputSelect));

        server.send(200, "text/plain", "Audio Settings Saved");
    });

    webSocket.onEvent(onWebSocketEvent);
    ElegantOTA.begin(&server);
    webSocket.begin();
    server.begin();
    Serial.println("[SYSTEM] HTTP Server and WebSocket Started");
}

void startAPMode() {
    Serial.println("Starting Access Point mode...");

    // The ESP32 WiFi driver keeps retrying a STA connection attempt on its
    // own even after our app-level 15s timeout in checkWiFiConnection()
    // gives up on it - calling softAP() straight into that can leave the
    // driver stuck tearing down the still-active STA attempt for a long
    // time before the AP actually comes up. Explicitly stopping STA and
    // switching mode first avoids racing that teardown.
    WiFi.disconnect();
    WiFi.mode(WIFI_AP);

    WiFi.softAP(apSSID, apPassword);
    Serial.print("AP IP Address: ");
    Serial.println(WiFi.softAPIP());
}

void handleRoot() {
  server.send(200, "text/html", html);
}

void handleControl() {
    String cmd = server.arg("cmd"); 
    DEBUG_LOG("[WEB DEBUG] handleControl received endpoint query! cmd = '%s'\n", cmd.c_str());
    
    if (cmd == "readytoggle") {
        String state = server.arg("state");
        applyReadyRequired(state == "on");
        pushSyncSetting("readyRequired", readyRequired ? "true" : "false");
    }
    else if (cmd == "tapouttoggle") {
        String state = server.arg("state");
        applyTapoutEnabled(state == "on");
        pushSyncSetting("tapoutEnabled", tapoutEnabled ? "true" : "false");
    }
    else {
        // Push to the configured sync target (if any) before queueing
        // locally - since pushSyncCommand() blocks on the HTTP round trip,
        // this gives the peer's copy of the command a small head start over
        // this unit's own state machine instead of stacking strictly after
        // it. Scoped to match-control commands only, same set the old
        // LoRa-based version relayed - and, like all of those, only when the
        // command actually came from the web UI. A remote's button press
        // (including time-select) queues straight into processCommand()
        // without ever reaching this handler, so it stays local - remotes
        // already get multi-timer behavior for free via direct pairing to
        // both units, not through the sync link (see config.h's note on
        // pushSyncSetting's extern declaration).
        if (cmd == "start" || cmd == "pause" || cmd == "reset" || cmd == "clockOff") {
            pushSyncCommand(cmd.c_str());
        } else if (cmd == "switch") {
            // Pushes the resulting absolute time rather than relaying the
            // toggle itself - relaying "switch" as a raw toggle command is
            // what caused two bound timers to drift permanently out of
            // sync before (any single missed/guarded application on the
            // peer left both sides toggling from a different base forever
            // after). Computed here rather than waiting for
            // processCommand() to apply it, since that function is also
            // reached by remote presses and would no longer know this one
            // came from the web.
            int newCountdownTime = (countdown_time == 120) ? 180 : 120;
            pushSyncSetting("time", String(newCountdownTime / 60) + "," + String(newCountdownTime % 60));
        }

        queueCommand(cmd.c_str());
    }
    server.send(200, "text/plain", "OK");
}

void pushSyncCommand(const char* cmd) {
    if (syncTargetIP.length() == 0) return;

    // Bounded timeout so an unreachable/misconfigured peer can only ever
    // stall this HTTP request handler briefly, never hang the timer - match
    // control itself doesn't depend on this call succeeding.
    HTTPClient http;
    http.setTimeout(300);
    http.begin("http://" + syncTargetIP + "/synccmd?cmd=" + String(cmd));
    http.GET();
    http.end();
}

void pushSyncSetting(const char* type, const String& value) {
    if (syncTargetIP.length() == 0) return;

    HTTPClient http;
    http.setTimeout(300);
    http.begin("http://" + syncTargetIP + "/syncsetting?type=" + String(type) + "&value=" + value);
    http.GET();
    http.end();
}

void pushAllSyncSettings() {
    char hexColor[7];
    snprintf(hexColor, sizeof(hexColor), "%02X%02X%02X", digitColor.r, digitColor.g, digitColor.b);
    pushSyncSetting("color", hexColor);

    pushSyncSetting("brightness", String(systemBrightness));
    pushSyncSetting("flip", displayInverted ? "true" : "false");
    pushSyncSetting("audio", String(audioEnabled ? "true" : "false") + "," +
                              String(remoteAudioEnabled ? "true" : "false") + "," +
                              String(audioOutputSelect));
    pushSyncSetting("readyRequired", readyRequired ? "true" : "false");
    pushSyncSetting("tapoutEnabled", tapoutEnabled ? "true" : "false");
    pushSyncSetting("time", String(current_time / 60) + "," + String(current_time % 60));

    if (currentState == CLOCK_MODE) {
        struct tm timeinfo;
        if (getLocalTime(&timeinfo)) {
            pushSyncSetting("clockOn", String(timeinfo.tm_hour) + "," + String(timeinfo.tm_min) + "," + String(timeinfo.tm_sec));
        }
    }
}

// Each of these is shared between the locally-originated /setXXX handler and
// the /syncsetting receiver (see initNetwork()), so a setting synced from a
// peer takes effect and persists exactly like a locally-made change.

void applyDigitColor(uint32_t hex) {
    digitColor = CRGB(hex);
    preferences.begin("settings", false);
    preferences.putUInt("digitColor", hex);
    preferences.end();
    updateLEDs();
}

void applyBrightnessSetting(int val) {
    systemBrightness = constrain(val, 10, 230);
    preferences.begin("settings", false);
    preferences.putUChar("brightness", systemBrightness);
    preferences.end();
    FastLED.setBrightness(systemBrightness);
    needsLEDUpdate = true;
}

void applyDisplayInverted(bool inverted) {
    displayInverted = inverted;
    preferences.begin("settings", false);
    preferences.putBool("dispInv", displayInverted);
    preferences.end();

    needsLEDUpdate = true;

    if (currentState == CLOCK_MODE) {
        handleClockMode();
    } else {
        updateLEDs();
    }

    setBorder();
}

void applySettingsAudio(bool enabled, bool remoteEnabled, uint8_t output) {
    audioEnabled = enabled;
    remoteAudioEnabled = remoteEnabled;
    audioOutputSelect = output;

    preferences.begin("settings", false);
    preferences.putBool("audioEnabled", audioEnabled);
    preferences.putBool("remoteAudio", remoteAudioEnabled);
    preferences.putUChar("audioOutput", audioOutputSelect);
    preferences.end();
}

void applyReadyRequired(bool required) {
    readyRequired = required;
    preferences.begin("settings", false);
    preferences.putBool("readyRequired", readyRequired);
    preferences.end();

    // setBorder()'s color depends on readyRequired combined with
    // redReady/blueReady, not readyRequired alone - if both were already
    // marked ready, toggling this could land on an identical border color
    // with no visible change. Force both back to not-ready so the border
    // always visibly reflects the new setting.
    redReady = false;
    blueReady = false;

    if (currentState != RUNNING) setBorder();
}

void applyTapoutEnabled(bool enabled) {
    tapoutEnabled = enabled;
    preferences.begin("settings", false);
    preferences.putBool("tapoutEnabled", tapoutEnabled);
    preferences.end();

    Serial.printf("[SYSTEM] Tapout Functionality updated and saved: %s\n", tapoutEnabled ? "ENABLED" : "DISABLED");
}

void applyClockMode(int hour, int minute, int s) {
    struct tm tm;
    tm.tm_hour = hour; tm.tm_min = minute; tm.tm_sec = s;
    tm.tm_year = 2026 - 1900; tm.tm_mon = 4; tm.tm_mday = 10;
    time_t t = mktime(&tm);
    struct timeval now = { .tv_sec = t };
    settimeofday(&now, NULL);

    currentState = CLOCK_MODE;

    preferences.begin("settings", false);
    preferences.putBool("clockActive", true);
    preferences.end();

    for (int i = 0; i < BORDER_LED_COUNT; i++) setBorderLEDs(i, CRGB::Black);
    for (int i = 0; i < DIGIT_LED_COUNT; i++) setDigitLEDs(i, CRGB::Black);

    if (hour == 0) hour = 12;
    if (hour > 12) hour -= 12;

    if (!displayInverted) {
        setDigit(hour / 10, 0, false);
        setDigit(hour % 10, 49, false);
        setColon();
        setDigit(minute / 10, 150, true);
        setDigit(minute % 10, 101, true);
    } else {
        setDigit(minute % 10, 0, false);
        setDigit(minute / 10, 49, false);
        setColon();
        setDigit(hour % 10, 150, true);
        setDigit(hour / 10, 101, true);
    }

    for (int i = 0; i < BORDER_LED_COUNT; i++)
        setBorderLEDs(i, ORANGE);

    applyDoubleSidedMirror();
    showLeds();
    needsLEDUpdate = false;
}

// Clamps to a sane MM:SS range (0-60 minutes, 0-59 seconds) - guards both
// manual entry (client-side already clamps, but that's bypassable) and
// values arriving over the sync link from a peer.
static void clampMinSec(int& m, int& s) {
    if (m < 0) m = 0;
    if (m > 60) m = 60;
    if (s < 0) s = 0;
    if (s > 59) s = 59;
}

// One-shot: only current_time, not countdown_time - affects the display for
// the upcoming match only. Reset still falls back to whatever countdown_time
// already was (the 2/3-min default, or a previously-set Match Time).
void applyOneOffTime(int m, int s) {
    if (currentState == RUNNING || currentState == PRE_COUNTDOWN_LOOP) return;
    clampMinSec(m, s);

    current_time = (m * 60) + s;
    currentState = IDLE;

    updateClient();
    updateLEDs();
}

// Persistent for the rest of this boot (not written to NVS - a custom
// event length isn't meant to outlive a reboot the way the 2/3-min default
// does): sets countdown_time too, so Reset keeps returning to this value
// instead of whichever preset was active before. The "switch" 2/3-min
// toggle can still override it same as always - this isn't a third,
// protected tier, just a different starting point for the same knob.
void applyMatchTime(int m, int s) {
    // Guards a match in progress on whichever side actually applies this -
    // the HTTP handlers also check up front for their own 403 response, but
    // this is what protects the /syncsetting receive path, where there's no
    // separate check: a peer's active match shouldn't get yanked back to
    // IDLE just because someone typed a time into a bound timer's own page.
    if (currentState == RUNNING || currentState == PRE_COUNTDOWN_LOOP) return;
    clampMinSec(m, s);

    countdown_time = (m * 60) + s;
    current_time = countdown_time;
    currentState = IDLE;

    updateClient();
    updateLEDs();
}

void handleSetTime() {
    if (currentState == RUNNING || currentState == PRE_COUNTDOWN_LOOP) {
        server.send(403, "text/plain", "Cannot set time while match is active!");
        return;
    }

    int m = server.arg("m").toInt();
    int s = server.arg("s").toInt();

    applyOneOffTime(m, s);
    pushSyncSetting("oneOffTime", String(m) + "," + String(s));

    server.send(200, "text/plain", "Time Updated");
}

void handleSetMatchTime() {
    if (currentState == RUNNING || currentState == PRE_COUNTDOWN_LOOP) {
        server.send(403, "text/plain", "Cannot set time while match is active!");
        return;
    }

    int m = server.arg("m").toInt();
    int s = server.arg("s").toInt();

    applyMatchTime(m, s);
    pushSyncSetting("time", String(m) + "," + String(s));

    server.send(200, "text/plain", "Match Time Updated");
}

void updateClient() {
  int minutes = current_time / 60;
  int seconds = current_time % 60;
  char buffer[6];
  snprintf(buffer, sizeof(buffer), "%02d:%02d", minutes, seconds);
  webSocket.broadcastTXT(buffer);
}

void onWebSocketEvent(uint8_t num, WStype_t type, uint8_t * payload, size_t length) {}

void handleSetWiFi() {
    String ssid = server.arg("ssid");
    String pass = server.arg("pass");
    
    if (ssid.length() > 0 && pass.length() > 0) {
        preferences.begin("wifi", false);
        preferences.putString("ssid", ssid);
        preferences.putString("pass", pass);
        preferences.end();
        
        server.send(200, "text/html", "<h1>WiFi Credentials Saved! Rebooting...</h1>");
        delay(3000);
        ESP.restart();
    } else {
        server.send(200, "text/html", "<h1>Invalid Input - Both SSID and Password are required</h1>");
    }
}

void handleClearWiFi() {
    preferences.begin("wifi", false);
    preferences.remove("ssid");
    preferences.remove("pass");
    preferences.end();

    server.send(200, "text/html", "<h1>WiFi Credentials Cleared! Rebooting...</h1>");
    delay(3000);
    ESP.restart();
}

void connectWiFi() {
    preferences.begin("wifi", true);
    String ssid = preferences.getString("ssid", "");
    String pass = preferences.getString("pass", "");
    preferences.end();

    configuredSSID = ssid;

    if (ssid.length() == 0 || ssid == "Disconnected") {
        startAPMode();
        return;
    }

    WiFi.begin(ssid.c_str(), pass.c_str());
    startAttemptTime = millis(); 
    currentState = CONNECTING;   
}

void checkWiFiConnection() {
    if (currentState != CONNECTING) return;

    bool connectionFinished = false;
    bool connectionFailed = false;

    if (WiFi.status() == WL_CONNECTED) {
        wifiEverConnected = true;

        static bool serversStarted = false;
        if (!serversStarted) {
            server.begin();
            webSocket.begin();
            webSocket.onEvent(onWebSocketEvent);

            Serial.println("\n[NETWORK] WiFi Connected successfully!");
            Serial.print("[NETWORK] Local IP Address: http://");
            Serial.println(WiFi.localIP());

            configTime(0, 0, "pool.ntp.org", "time.nist.gov");
            setenv("TZ", "CST6CDT,M3.2.0,M11.1.0", 1);
            tzset();

            serversStarted = true;
        }
        connectionFinished = true;
    } 
    else if (millis() - startAttemptTime > 15000) {
        startAPMode();
        preferences.begin("settings", false);
        preferences.putBool("clockActive", false);
        preferences.end();
        connectionFinished = true;
        connectionFailed = true;
    }

    if (connectionFinished) {
        preferences.begin("settings", true);
        bool clockActive = preferences.getBool("clockActive", false);
        preferences.end();

        if (clockActive && !connectionFailed) {
            currentState = CLOCK_MODE;

            Serial.println("[SYSTEM] Performing sequential inline timezone detection...");
            HTTPClient http;
            http.setTimeout(2500); 
            http.begin("http://worldtimeapi.org/api/ip.txt");
            
            int httpCode = http.GET();
            String posixString = "";
            
            if (httpCode == HTTP_CODE_OK) {
                String payload = http.getString();
                int tzOffsetIdx = payload.indexOf("utc_offset: ");
                
                if (tzOffsetIdx != -1) {
                    int startOffset = tzOffsetIdx + 12;
                    int endOffset = payload.indexOf('\n', startOffset);
                    String rawOffset = payload.substring(startOffset, endOffset);
                    rawOffset.trim();
                    
                    int hoursOffset = rawOffset.substring(1, 3).toInt();
                    char sign = rawOffset.charAt(0);
                    
                    if (sign == '-') {
                        posixString = "GMT" + String(hoursOffset);
                    } else {
                        posixString = "GMT-" + String(hoursOffset);
                    }
                    
                    if (payload.indexOf("America/") != -1) {
                        int dstOffset = hoursOffset - 1;
                        posixString += "GMT+" + String(dstOffset) + ",M3.2.0,M11.1.0";
                    }
                }
            }
            http.end();

            if (posixString.length() > 0) {
                Serial.printf("[SYSTEM] Found region rule inline: %s\n", posixString.c_str());
                setenv("TZ", posixString.c_str(), 1);
                tzset();
            } else {
                Serial.println("[SYSTEM] Network lookup failed or timed out. Falling back to Central Time.");
                setenv("TZ", "CST6CDT,M3.2.0,M11.1.0", 1);
                tzset();
            }

            struct tm timeinfo;
            if (getLocalTime(&timeinfo)) {
                Serial.println("[SYSTEM] Inline clock calibration complete.");
            }

            handleClockMode();
            setBorder();
        } 
        else {
            currentState = IDLE;
            updateLEDs();
            setBorder();
        }

        applyDoubleSidedMirror();
        needsLEDUpdate = true;
        updateClient();
        
    } 
    else if (connectionFailed) {
        Serial.println("[SYSTEM WARNING] WiFi Connection failed! Gating in IDLE mode on Access Point hotspot.");
    }
}

void loadSavedSettings() {
    loraLoadSavedRemotes();
    espnowLoadSavedRemotes(); // both recompute the combined redPaired/bluePaired/judgePaired

    preferences.begin("settings", true);
    readyRequired = preferences.getBool("readyRequired", false); 
    timeSelState = preferences.getBool("timeSelState", false); 
    systemBrightness = preferences.getUChar("brightness", 127); 
    displayInverted = preferences.getBool("dispInv", false); 
    tapoutEnabled = preferences.getBool("tapoutEnabled", true); 

    audioEnabled = preferences.getBool("audioEnabled", true);
    remoteAudioEnabled = preferences.getBool("remoteAudio", true);
    audioOutputSelect = preferences.getUChar("audioOutput", 0);
    syncTargetIP = preferences.getString("syncIP", "");
    timerName = preferences.getString("timerName", "");
    uint32_t savedColor = preferences.getUInt("digitColor", 0xFF0000);

    preferences.end();
    FastLED.setBrightness(systemBrightness);
    digitColor = CRGB(savedColor);

    countdown_time = timeSelState ? 180 : 120; 
    current_time = countdown_time; 
}

void setup() {
  Serial.begin(115200);

  loadSavedSettings();
  initDisplay();
  initNetwork();

  // Must stay ahead of the FastLED.show() below. FastLED.show() is
  // asynchronous on ESP32 (RMT clocks the frame out in the background after
  // show() returns), and loraInit() blocks for ~1s+ between its radio reset
  // delay and AT command retries. With loraInit() after the show, that
  // blocking starved the RMT refill mid-frame and latched a corrupted
  // rainbow into the strips until the next redraw. Verified on a scope.
  loraInit();

  // esp_now_init() rides the WiFi radio and returns promptly (no UART/AT
  // round trips like loraInit()), so it doesn't need the same ordering care.
  espnowInit();

  // Always double-sided, on every hardware revision - single-sided units
  // just clock out a few extra, physically-nonexistent pixels at the end of
  // the strip and ignore them, a negligible timing cost. That means GPIO22
  // never needs to double as a hardware strap, so it's free for the LoRa
  // UART on every board without any runtime detection to keep the two uses
  // apart.
  isDoubleSided = true;

  updateLEDs();
  setBorder();
  applyDoubleSidedMirror(); // else side B stays dark until loop()'s first redraw
  needsLEDUpdate = false;
  showLeds();

  pinMode(RESET_BTN, INPUT_PULLUP);
  pinMode(PAUSE_BTN, INPUT_PULLUP);
  pinMode(START_BTN, INPUT_PULLUP);
  pinMode(TIME_SEL_SW, INPUT_PULLUP);
  pinMode(BLUE_BTN, INPUT_PULLUP);
  pinMode(RED_BTN, INPUT_PULLUP);
  pinMode(BUZZ_PIN, OUTPUT);
  pinMode(RELAY_PIN, OUTPUT);
}

void loop() {
  static uint32_t lastFrameTime = 0;
  uint32_t currentMillis = millis();

  server.handleClient();
  webSocket.loop();
  ElegantOTA.loop();
  loraPoll(); // drained every loop iteration, not gated to 20ms like the rest below

  // Auto-reconnect: only for a unit that has actually joined a network
  // before (wifiEverConnected) - boot-time behavior (stay in AP mode if
  // never configured) is untouched. WiFi.reconnect() just calls
  // esp_wifi_connect() and returns immediately; it does not block waiting
  // for the result, so this can never hang timer operation, which doesn't
  // depend on WiFi at all. On its own 5s cadence so a drop isn't retried
  // every loop() iteration.
  //
  // Also held off for 50ms after the last LED push (lastLedShowMillis):
  // FastLED.show() is asynchronous, so a frame can still be clocking out of
  // RMT well after show() returns - WS2812 timing for this strip length
  // works out to roughly 10ms worst case, 50ms leaves comfortable margin.
  // WiFi driver calls run at high interrupt priority and can briefly starve
  // that ISR if they land mid-transfer, corrupting the frame into a stray
  // burst of wrong-colored pixels. Confirmed on hardware: this reconnect
  // check landing during a paused-blink redraw produced exactly that.
  static uint32_t lastReconnectAttempt = 0;
  if (wifiEverConnected && WiFi.status() != WL_CONNECTED &&
      currentMillis - lastReconnectAttempt >= 5000 &&
      currentMillis - lastLedShowMillis >= 50) {
    lastReconnectAttempt = currentMillis;
    Serial.println("[NETWORK] Connection lost, attempting to reconnect...");
    WiFi.reconnect();
  }

  if (currentMillis - lastFrameTime >= 20) {
    lastFrameTime = currentMillis;

    checkAudioTimeout();

    checkButtons();

    if (pairingMode && currentMillis - pairingModeStarted > PAIRING_MODE_TIMEOUT_MS) {
        pairingMode = false;
        Serial.println("[SYSTEM] Pairing Mode timed out with no remote detected.");
    }

    char nextCmd[CMD_MAX_LEN] = "";
    portENTER_CRITICAL(&queueMux);
    if (cmdQueueCount > 0) {
        memcpy(nextCmd, commandQueue[cmdQueueHead], CMD_MAX_LEN);
        cmdQueueHead = (cmdQueueHead + 1) % CMD_QUEUE_SIZE;
        cmdQueueCount--;
    }
    portEXIT_CRITICAL(&queueMux);

    if (nextCmd[0] != '\0') {
        processCommand(nextCmd); // implicit char* -> String, safely outside the critical section
    }

    switch(currentState) {
      case CONNECTING:
        handleConnectingAnimation();
        checkWiFiConnection();
      break;
      case PRE_COUNTDOWN_INIT:
        startPreCountdown();
      break;
      case PRE_COUNTDOWN_LOOP:
        handlePreCountdownAnimation(); 
      break;
      case RUNNING:
        updateTimer();
      break;
      case PAUSED:
        handlePausedBlink();
      break;
      case FINISHED:
      break;
      case CLOCK_MODE:
        handleClockMode();
      break;
      case TAPOUT:
        handleTapoutAnimation();
      break;
    }

    if (needsLEDUpdate) {
        applyDoubleSidedMirror();
        showLeds();
        needsLEDUpdate = false;
    }
  }
}